/*	$OpenBSD: flex.skl,v 1.5 1997/07/25 21:05:28 mickey Exp $	*/

/* A lexical scanner generated by flex */

/* Scanner skeleton version:
 * $Header$
 */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5

#include <stdio.h>


/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>
#include <unistd.h>

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#ifdef __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern int yyleng;
extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		yyless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		*yy_cp = yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext_ptr )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int yy_size_t;


struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
	};

static YY_BUFFER_STATE yy_current_buffer = 0;

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer


/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;

static int yy_n_chars;		/* number of characters read into yy_ch_buf */


int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 1;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart YY_PROTO(( FILE *input_file ));

void yy_switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void yy_load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE yy_create_buffer YY_PROTO(( FILE *file, int size ));
void yy_delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void yy_init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));
void yy_flush_buffer YY_PROTO(( YY_BUFFER_STATE b ));
#define YY_FLUSH_BUFFER yy_flush_buffer( yy_current_buffer )

YY_BUFFER_STATE yy_scan_buffer YY_PROTO(( char *base, yy_size_t size ));
YY_BUFFER_STATE yy_scan_string YY_PROTO(( yyconst char *yy_str ));
YY_BUFFER_STATE yy_scan_bytes YY_PROTO(( yyconst char *bytes, int len ));

static void *yy_flex_alloc YY_PROTO(( yy_size_t ));
static void *yy_flex_realloc YY_PROTO(( void *, yy_size_t ));
static void yy_flex_free YY_PROTO(( void * ));

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (yy_current_buffer->yy_at_bol)

typedef unsigned char YY_CHAR;
FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;
typedef int yy_state_type;
extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state YY_PROTO(( void ));
static yy_state_type yy_try_NUL_trans YY_PROTO(( yy_state_type current_state ));
static int yy_get_next_buffer YY_PROTO(( void ));
static void yy_fatal_error YY_PROTO(( yyconst char msg[] ));

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yytext_ptr = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 27
#define YY_END_OF_BUFFER 28
static yyconst short int yy_accept[330] =
    {   0,
        0,    0,    0,    0,    0,    0,   28,   26,    1,    5,
        9,   26,   26,   19,   26,    8,   26,   25,   25,   25,
       11,   10,   24,   24,   24,   26,   25,    7,    4,    7,
        7,    7,    4,    7,    7,    7,    7,    4,    4,    7,
        7,    7,   26,    7,   21,    9,   21,   21,   22,   21,
       21,   21,   21,   21,   10,   20,   20,   20,   21,   21,
        1,    9,    0,    6,   15,   14,   23,   25,    0,   25,
       25,   25,   25,    0,   24,   24,   24,    0,    2,    7,
        7,    7,    7,    7,    7,    7,    7,    7,    7,    7,
        7,    7,    7,    7,    3,    3,   21,    9,   15,   14,

       21,   21,   21,   21,   21,   21,   21,   21,   20,   20,
       20,    0,    0,    0,   25,   18,   24,   24,    7,    7,
        7,    7,    7,    7,    7,   21,   21,   21,   21,   18,
       20,   20,    0,    0,    0,    0,   24,   24,    7,    7,
        7,    7,    7,    7,   21,   21,   21,   21,   20,   20,
        0,    0,    0,    0,   24,   24,    7,    7,    7,    7,
        7,    7,   21,   21,   21,   21,   20,   20,    0,    0,
        0,    0,   24,   24,    7,    7,    7,    7,    7,    7,
       21,   21,   21,   21,   20,   20,   16,   16,   16,    0,
       24,    0,   13,    7,    7,    7,    7,    7,   16,   16,

       16,   21,   20,    0,   16,   16,   16,   24,    7,    7,
        7,    7,    7,   21,   16,   16,   16,   20,    0,   17,
       17,   17,   16,    0,   12,    7,    7,    7,    7,    7,
       21,   17,   17,   17,   16,    0,    0,   17,   17,   17,
       17,    7,    7,    7,    7,    7,    7,   21,   21,   17,
       17,   17,   17,    0,    0,    0,   17,   17,   17,    7,
        7,    7,    7,    7,    7,   21,   21,   21,   17,   17,
       17,    0,    0,    0,    0,    7,    7,    7,    7,   21,
       21,   21,   21,    0,    0,    0,    0,    7,    7,    7,
        7,   21,   21,   21,   21,    0,    0,    0,    0,    7,

        7,    7,    7,   21,   21,   21,   21,   16,   16,   16,
        0,    7,    7,    7,    7,   16,   16,   16,   21,   16,
       16,    7,    7,   16,   16,   16,    7,   16,    0
    } ;

static yyconst int yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    4,    1,    5,    1,    6,    1,    1,    7,
        8,    1,    9,   10,   11,   12,   13,   14,   15,   16,
       17,   18,   18,   19,   19,   19,   19,   20,    1,    1,
       21,    1,    1,    1,   22,   23,   23,   24,   23,   23,
       23,   23,   23,   23,   23,   23,   23,   25,   26,   27,
       23,   23,   28,   23,   23,   23,   29,   23,   23,   23,
        1,   30,    1,    1,   31,    1,   32,   32,   32,   32,

       32,   32,   32,   32,   32,   32,   32,   32,   32,   32,
       32,   32,   32,   32,   32,   32,   32,   32,   32,   32,
       32,   32,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst int yy_meta[33] =
    {   0,
        1,    2,    2,    1,    3,    1,    1,    4,    1,    2,
        5,    6,    7,    8,    8,    8,    8,    8,    9,    2,
       10,    5,    5,    5,    5,    5,    5,    5,    5,   11,
        5,    5
    } ;

static yyconst short int yy_base[386] =
    {   0,
        0,    0,   32,    0,   64,    0, 1225, 1342, 1221, 1342,
     1209, 1206,    0, 1342,    0, 1342,    0,   85,   93,   99,
     1342, 1342,  108,  110,  101,  122, 1196,    0, 1342, 1193,
       98,  118, 1342,  124,  148,  167,  173, 1342,    0,  191,
     1169, 1162,  128,  223,    0, 1171,    0,    0, 1342,    0,
      229,  259,  278,  284,    0,  302, 1147, 1142,  130,  334,
     1160, 1149, 1148, 1342,    0,    0,    0, 1129,  119, 1125,
      351,  356, 1124,    0, 1109,  111,  113,  141, 1342,    0,
     1130,  138,  203,  173,  364,  370, 1121,    0,  376,  395,
      416,    0, 1105, 1103,  148, 1342,    0, 1117,    0,    0,

      237,  426,  432, 1098,    0,  438,  457,  487,    0, 1072,
     1061, 1073, 1068,  227, 1063, 1054,  199,  212,  506,  512,
      518, 1053,  536, 1034, 1026,  546,  552,  558, 1033,  576,
     1021,  929,  232,  926,  895,  871,  215,  223,  593,  864,
        0,  599,  824,  759,  605,  756,    0,  611,  732,  622,
      620,  593,  242,  592,  225,  231,  619,  625,  631,  591,
      574,  577,  638,  644,  650,  588,  571,  574,  289,  584,
      583,  582,  316,  334,  655,  581,    0,  661,  563,  342,
      667,  579,    0,  673,  561,  357,  574,  573,  243,  572,
      286,  395, 1342,  680,  686,  692,  567,  554,  698,  704,

      710,  547,  532,  715,  542,  541,  540,  407,  721,  539,
        0,  727,  410,  733,  538,    0,  739,  411,  538,  535,
      337,  747,  533,  412, 1342,  755,  761,  767,  336,  526,
      775,  781,  787,  420,  525,  342,  507,  504,  386,  503,
      459,  793,  502,  799,  804,  810,  465,  815,  501,  821,
      826,  832,  470,  500,  495,  399,  483,  471,  487,  839,
      845,  851,  856,  863,  490,  870,  876,  882,  887,  894,
      495,  444,  464,  460,  453,  899,  427,    0,  905,  911,
      398,    0,  917,  394,  351,  407,  349,  925,  931,  937,
      341,  944,  950,  956,  336,  452,  325,  310,  267,  961,

      257,    0,  967,  973,  214,    0,  979,    0,    0,  182,
      181,  985,  474,  991,  146,  996,  482, 1002,  135, 1342,
        0,    0, 1007,    0, 1012, 1342,    0,    0, 1342, 1030,
     1041, 1052, 1063, 1068, 1073, 1078, 1087, 1097, 1108, 1119,
     1128, 1139, 1149, 1160, 1171, 1182, 1193, 1197, 1202, 1211,
     1221, 1227, 1231, 1235, 1237, 1241, 1244, 1248, 1252, 1254,
     1258, 1260, 1263, 1266, 1269, 1272, 1276, 1280, 1282, 1286,
     1290, 1294, 1298, 1302, 1306, 1308, 1312, 1315, 1319, 1323,
     1325, 1329, 1330, 1332,   90
    } ;

static yyconst short int yy_def[386] =
    {   0,
      329,    1,  329,    3,  329,    5,  329,  329,  329,  329,
      329,  330,  331,  329,  332,  329,  333,  334,  334,   19,
      329,  329,  335,  335,   24,  329,  336,  337,  329,  337,
      338,  339,  329,  340,  329,   35,   35,  329,  337,  329,
       40,   40,  341,  342,  343,  343,  343,  344,  329,  345,
      346,  329,   52,   52,  343,  329,   56,   56,  343,  347,
      329,  329,  330,  329,  331,  332,  333,  334,  348,  334,
       20,   20,  336,  349,   24,   24,   24,  329,  329,  337,
      337,  338,  339,  340,   35,  337,   85,   35,   35,  342,
      350,   40,   40,   40,  329,  329,  343,  343,  344,  345,

      346,   52,  343,  102,   52,   52,  347,  351,   56,   56,
       56,  352,  353,  354,  334,  349,   24,   24,  337,  119,
      119,   85,  350,   40,   40,  343,  126,  126,  102,  351,
       56,   56,  355,  329,  352,  356,   24,   24,  337,  337,
      119,  119,   40,   40,  343,  343,  126,  126,   56,   56,
      357,  358,  359,  329,   24,   24,  119,  157,  157,  337,
       40,   40,  126,  163,  163,  343,   56,   56,  360,  329,
      357,  361,   24,   24,  337,  337,  157,  157,   40,   40,
      343,  343,  163,  163,   56,   56,  362,  363,  364,  329,
       24,  329,  329,  337,  194,  194,  337,   40,  343,  199,

      199,  343,   56,  329,  329,  362,  365,   24,  337,  337,
      194,  194,   40,  343,  343,  199,  199,   56,  366,  367,
      368,  329,  329,  329,  329,  337,  226,  226,  226,  337,
      343,  231,  231,  231,  343,  369,  329,  370,  371,  372,
      329,  337,  337,  228,  228,  245,  337,  343,  343,  233,
      233,  251,  343,  373,  374,  375,  372,  372,  329,  337,
      260,  260,  245,  245,  337,  343,  266,  266,  251,  251,
      343,  376,  329,  373,  377,  337,  337,  260,  260,  343,
      343,  266,  266,  378,  379,  380,  329,  260,  288,  288,
      337,  266,  292,  292,  343,  381,  329,  378,  382,  337,

      337,  288,  288,  343,  343,  292,  292,  383,  381,  384,
      329,  337,  300,  312,  337,  343,  304,  316,  343,  329,
      385,  337,  337,  343,  343,  329,  337,  343,    0,  329,
      329,  329,  329,  329,  329,  329,  329,  329,  329,  329,
      329,  329,  329,  329,  329,  329,  329,  329,  329,  329,
      329,  329,  329,  329,  329,  329,  329,  329,  329,  329,
      329,  329,  329,  329,  329,  329,  329,  329,  329,  329,
      329,  329,  329,  329,  329,  329,  329,  329,  329,  329,
      329,  329,  329,  329,  329
    } ;

static yyconst short int yy_nxt[1375] =
    {   0,
        8,    9,   10,   11,   12,   13,   14,    8,   15,   16,
        8,    8,   17,   18,   19,   20,   18,   18,   18,   21,
       22,   23,   23,   23,   24,   23,   25,   23,   23,   26,
        8,   27,   28,    9,   29,   30,   28,   31,   28,   28,
       32,   33,   28,   28,   34,   35,   36,   37,   35,   35,
       35,   38,   39,   40,   40,   40,   41,   40,   42,   40,
       40,   43,   28,   44,   45,    9,   10,   46,   47,   48,
       45,   49,   50,   16,   45,   45,   51,   52,   53,   54,
       52,   52,   52,   21,   55,   56,   56,   56,   57,   56,
       58,   56,   56,   59,   45,   60,   69,  326,   70,   70,

       70,   70,   70,   70,   69,   80,   71,   71,   71,   71,
       71,   71,   72,   72,   72,   72,   72,   70,   73,   74,
       73,   74,   77,   78,   79,   80,   75,   65,   80,   95,
       79,   78,   79,  113,  114,   76,   75,  117,   75,   73,
      118,   73,   78,   79,   80,   80,  304,   66,   80,   78,
       79,   80,   80,   80,   80,   80,   80,  300,   85,   86,
       80,   87,   87,   87,   87,   87,   87,   65,   80,   85,
       85,   85,   85,   85,   85,   85,   85,   80,   85,   85,
       88,   88,   88,   88,   88,   88,   89,   89,   89,   89,
       89,   80,  296,   80,   80,   80,   80,   80,   80,   80,

      320,   90,   91,   80,   92,   92,   92,   92,   92,   92,
       80,   80,   92,   92,   92,   92,   92,   92,   92,   92,
      137,   92,   90,   80,   75,  304,   80,   80,   80,   80,
       80,   80,   66,   97,   91,   80,   67,   75,  133,  138,
       75,   97,  155,   80,   67,  134,  152,  153,   75,   97,
       75,  156,  173,  169,  174,  204,   75,   97,   97,   97,
      170,  205,   97,   97,   97,   97,   97,   97,  300,  102,
      103,   97,  104,  104,  104,  104,  104,  104,  296,   97,
      102,  102,  102,  102,  102,  102,  102,  102,   97,  102,
      102,  105,  105,  105,  105,  105,  105,  106,  106,  106,

      106,  106,   97,  188,  189,   97,   97,   97,   97,  208,
       97,   75,  107,  108,   97,  109,  109,  109,  109,  109,
      109,  296,   97,  109,  109,  109,  109,  109,  109,  109,
      109,   97,  109,  107,   97,  192,  296,   97,   97,   97,
       97,   75,   97,  192,  191,  108,   97,  280,  236,  247,
      247,  247,  276,  193,   97,  240,  255,  256,  192,   75,
      272,  193,  296,   97,   70,   70,   70,   70,   70,  115,
      115,  115,  115,  115,   68,   80,  193,   85,   85,   85,
       85,   85,   85,  119,  120,  121,  119,  119,  119,  122,
      122,  122,  122,  122,   85,   80,  192,  236,   80,   80,

       80,   80,   80,   80,  258,  296,   91,   80,  224,  280,
      272,  224,  224,  224,  193,   80,   80,  273,  296,   80,
       80,   80,   80,   80,   80,  297,  225,   80,   80,  225,
      225,  225,   75,  253,  253,  253,   80,   97,  276,  102,
      102,  102,  102,  102,  102,  126,  127,  128,  126,  126,
      126,  129,  129,  129,  129,  129,  102,   97,  285,  286,
       97,   97,   97,   97,  272,   97,  309,  310,  108,   97,
      236,  272,  259,  259,  259,  272,  242,   97,  265,  265,
      265,  248,  329,  271,  271,  271,   97,   97,  312,  312,
       97,   97,   97,   97,  236,   97,  316,  316,   97,   97,

      259,  259,  259,  265,  265,  265,  272,   97,  271,  271,
      271,  272,  248,  242,  236,  236,   97,  139,  236,  140,
      140,  140,  140,  140,  140,  141,  141,  141,  141,  141,
      141,  142,  142,  142,  142,  142,   80,  214,  209,   80,
       80,   80,   80,   80,   80,  204,  236,   91,   80,  236,
      214,  209,  204,  204,  204,  218,   80,  145,  181,  146,
      146,  146,  146,  146,  146,  147,  147,  147,  147,  147,
      147,  148,  148,  148,  148,  148,   97,  213,  175,   97,
       97,   97,   97,  169,   97,  204,  204,  108,   97,  203,
      181,  198,  175,  169,  169,  169,   97,  186,  185,  145,

      180,  179,  139,  133,  169,   97,  157,  158,  159,  157,
      157,  157,  160,  160,  160,  160,  160,   80,  163,  164,
      165,  163,  163,  163,  166,  166,  166,  166,  166,   97,
      175,  169,  176,  176,  176,  176,  176,  176,  177,  177,
      177,  177,  177,  177,  178,  178,  178,  178,  178,  181,
      168,  182,  182,  182,  182,  182,  182,  183,  183,  183,
      183,  183,  183,  184,  184,  184,  184,  184,  194,  195,
      196,  194,  194,  194,  197,  197,  197,  197,  197,   80,
      199,  200,  201,  199,  199,  199,  202,  202,  202,  202,
      202,   97,  209,  210,  210,  210,  210,  210,  210,  211,

      211,  211,  211,  211,  211,  212,  212,  212,  212,  212,
      214,  215,  215,  215,  215,  215,  215,  216,  216,  216,
      216,  216,  216,  217,  217,  217,  217,  217,  219,  220,
      221,  222,  219,  219,  226,  227,  228,  229,  226,  226,
      230,  230,  230,  230,  230,   80,  231,  232,  233,  234,
      231,  231,  235,  235,  235,  235,  235,   97,  236,  167,
      241,  241,  241,  237,  237,  237,  242,  145,  243,  243,
      243,  243,  243,  243,  244,  244,  244,  244,  244,  244,
      245,  245,  245,  245,  245,  246,  248,  162,  249,  249,
      249,  249,  249,  249,  250,  250,  250,  250,  250,  250,

      251,  251,  251,  251,  251,  252,  260,  261,  262,  260,
      260,  260,  246,  246,  246,  246,  246,  263,  263,  263,
      263,  263,  264,  264,  264,  264,  264,  264,  266,  267,
      268,  266,  266,  266,  252,  252,  252,  252,  252,  269,
      269,  269,  269,  269,  270,  270,  270,  270,  270,  270,
      276,  161,  277,  277,  277,  277,  277,  277,  278,  278,
      278,  278,  278,  278,  279,  279,  279,  279,  279,  264,
      264,  264,  264,  264,   80,  139,  264,  264,  264,  264,
      264,  280,  133,  281,  281,  281,  281,  281,  281,  282,
      282,  282,  282,  282,  282,  283,  283,  283,  283,  283,

      270,  270,  270,  270,  270,   97,  133,  270,  270,  270,
      270,  270,  288,  289,  290,  288,  288,  288,  291,  291,
      291,  291,  291,   80,  292,  293,  294,  292,  292,  292,
      295,  295,  295,  295,  295,   97,  300,  133,  301,  301,
      301,  301,  301,  301,  302,  302,  302,  302,  302,  302,
      303,  303,  303,  303,  303,  304,  150,  305,  305,  305,
      305,  305,  305,  306,  306,  306,  306,  306,  306,  307,
      307,  307,  307,  307,  312,  313,  314,  312,  312,  312,
      315,  315,  315,  315,  315,   80,  316,  317,  318,  316,
      316,  316,  319,  319,  319,  319,  319,   97,  322,  322,

      322,  322,  322,  322,  323,  323,  323,  323,  323,  324,
      324,  324,  324,  324,  324,  325,  325,  325,  325,  325,
      327,  327,  327,  327,  327,  328,  328,  328,  328,  328,
       63,   63,   63,   63,   63,   63,   63,   63,   63,   63,
       63,   65,  149,   65,  103,   65,   65,   65,   65,   65,
       65,   65,   66,  144,   66,  143,   66,   66,   66,   66,
       66,   66,   66,   67,   86,   74,   67,   67,   67,   67,
       67,   67,   68,   68,   69,   68,   68,   75,   75,  133,
       75,   75,   73,   73,  133,   73,   73,   80,  132,   80,
       80,   80,   80,   80,   80,   80,   80,   82,  131,   82,

       82,   82,   82,   82,   82,   82,   82,   82,   83,  103,
       83,   83,   83,   83,   83,   83,   83,   83,   83,   84,
       98,   84,   84,   84,   84,   84,   84,   84,   84,   96,
      125,  124,   86,   81,   75,   74,   69,   96,   96,   90,
      329,   90,   90,   90,   90,   90,   90,   90,   90,   97,
       64,   97,   62,   97,   97,   97,   97,   97,   97,   97,
       99,   61,   99,  111,   99,   99,   99,   99,   99,   99,
       99,  100,  110,  100,   98,  100,  100,  100,  100,  100,
      100,  100,  101,   94,  101,  101,  101,  101,  101,  101,
      101,  101,  101,  107,   93,  107,   81,  107,  107,  107,

      107,  107,  107,  107,  112,  112,  116,   74,   64,  116,
      116,  123,   62,  123,  123,  123,  123,  123,  123,  123,
      123,  130,   61,  130,  329,  130,  130,  130,  130,  130,
      130,  130,  134,  329,  134,  134,  135,  329,  135,  135,
      136,  329,  136,  136,  151,  151,  154,  329,  154,  170,
      329,  170,  170,  171,  329,  171,  171,  172,  329,  172,
      172,  187,  187,  190,  329,  190,  205,  205,  205,  206,
      206,  206,  207,  207,  207,  223,  223,  237,  329,  237,
      237,  238,  329,  238,  238,  239,  329,  239,  239,  254,
      254,  240,  329,  240,  240,  257,  329,  257,  257,  258,

      329,  258,  258,  273,  329,  273,  273,  274,  329,  274,
      274,  275,  329,  275,  275,  284,  284,  287,  329,  287,
      297,  329,  297,  297,  298,  329,  298,  298,  299,  329,
      299,  299,  308,  308,  311,  329,  311,  320,  320,  321,
      321,    7,  329,  329,  329,  329,  329,  329,  329,  329,
      329,  329,  329,  329,  329,  329,  329,  329,  329,  329,
      329,  329,  329,  329,  329,  329,  329,  329,  329,  329,
      329,  329,  329,  329
    } ;

static yyconst short int yy_chk[1375] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,   18,  385,   18,   18,

       18,   18,   18,   18,   19,   31,   19,   19,   19,   19,
       19,   19,   20,   20,   20,   20,   20,   20,   23,   23,
       24,   24,   25,   26,   26,   32,   25,   31,   34,   43,
       43,   59,   59,   69,   69,   24,   76,   76,   77,   23,
       77,   24,   78,   78,   34,   82,  319,   32,   35,   95,
       95,   35,   35,   35,   35,   35,   35,  315,   35,   35,
       35,   35,   35,   35,   35,   35,   35,   82,   35,   35,
       35,   35,   35,   35,   35,   35,   35,   84,   35,   35,
       36,   36,   36,   36,   36,   36,   37,   37,   37,   37,
       37,   40,  311,   84,   40,   40,   40,   40,   40,   40,

      310,   40,   40,   40,   40,   40,   40,   40,   40,   40,
       83,   40,   40,   40,   40,   40,   40,   40,   40,   40,
      117,   40,   40,   44,  117,  305,   44,   44,   44,   44,
       44,   44,   83,   51,   44,   44,   51,  118,  114,  118,
      137,  101,  137,   44,  101,  114,  133,  133,  138,   51,
      155,  138,  155,  153,  156,  189,  156,  101,   51,   52,
      153,  189,   52,   52,   52,   52,  101,   52,  301,   52,
       52,   52,   52,   52,   52,   52,   52,   52,  299,   52,
       52,   52,   52,   52,   52,   52,   52,   52,   52,   52,
       52,   53,   53,   53,   53,   53,   53,   54,   54,   54,

       54,   54,   56,  169,  169,   56,   56,   56,   56,  191,
       56,  191,   56,   56,   56,   56,   56,   56,   56,   56,
       56,  298,   56,   56,   56,   56,   56,   56,   56,   56,
       56,   56,   56,   56,   60,  174,  297,   60,   60,   60,
       60,  173,   60,  180,  173,   60,   60,  295,  221,  229,
      229,  229,  291,  174,   60,  221,  236,  236,  186,  174,
      287,  180,  285,   60,   71,   71,   71,   71,   71,   72,
       72,   72,   72,   72,   72,   85,  186,   85,   85,   85,
       85,   85,   85,   86,   86,   86,   86,   86,   86,   89,
       89,   89,   89,   89,   89,   90,  192,  239,   90,   90,

       90,   90,   90,   90,  239,  284,   90,   90,  208,  281,
      256,  213,  218,  224,  192,   90,   91,  256,  286,   91,
       91,   91,   91,   91,   91,  286,  208,   91,   91,  213,
      218,  224,  208,  234,  234,  234,   91,  102,  277,  102,
      102,  102,  102,  102,  102,  103,  103,  103,  103,  103,
      103,  106,  106,  106,  106,  106,  106,  107,  272,  272,
      107,  107,  107,  107,  275,  107,  296,  296,  107,  107,
      241,  274,  241,  241,  241,  273,  247,  107,  247,  247,
      247,  253,  258,  253,  253,  253,  107,  108,  313,  313,
      108,  108,  108,  108,  257,  108,  317,  317,  108,  108,

      259,  259,  259,  265,  265,  265,  255,  108,  271,  271,
      271,  254,  249,  243,  240,  238,  108,  119,  237,  119,
      119,  119,  119,  119,  119,  120,  120,  120,  120,  120,
      120,  121,  121,  121,  121,  121,  123,  235,  230,  123,
      123,  123,  123,  123,  123,  223,  220,  123,  123,  219,
      215,  210,  207,  206,  205,  203,  123,  126,  202,  126,
      126,  126,  126,  126,  126,  127,  127,  127,  127,  127,
      127,  128,  128,  128,  128,  128,  130,  198,  197,  130,
      130,  130,  130,  190,  130,  188,  187,  130,  130,  185,
      182,  179,  176,  172,  171,  170,  130,  168,  167,  166,

      162,  161,  160,  154,  152,  130,  139,  139,  139,  139,
      139,  139,  142,  142,  142,  142,  142,  142,  145,  145,
      145,  145,  145,  145,  148,  148,  148,  148,  148,  148,
      157,  151,  157,  157,  157,  157,  157,  157,  158,  158,
      158,  158,  158,  158,  159,  159,  159,  159,  159,  163,
      150,  163,  163,  163,  163,  163,  163,  164,  164,  164,
      164,  164,  164,  165,  165,  165,  165,  165,  175,  175,
      175,  175,  175,  175,  178,  178,  178,  178,  178,  178,
      181,  181,  181,  181,  181,  181,  184,  184,  184,  184,
      184,  184,  194,  194,  194,  194,  194,  194,  194,  195,

      195,  195,  195,  195,  195,  196,  196,  196,  196,  196,
      199,  199,  199,  199,  199,  199,  199,  200,  200,  200,
      200,  200,  200,  201,  201,  201,  201,  201,  204,  204,
      204,  204,  204,  204,  209,  209,  209,  209,  209,  209,
      212,  212,  212,  212,  212,  212,  214,  214,  214,  214,
      214,  214,  217,  217,  217,  217,  217,  217,  222,  149,
      222,  222,  222,  222,  222,  222,  226,  146,  226,  226,
      226,  226,  226,  226,  227,  227,  227,  227,  227,  227,
      228,  228,  228,  228,  228,  228,  231,  144,  231,  231,
      231,  231,  231,  231,  232,  232,  232,  232,  232,  232,

      233,  233,  233,  233,  233,  233,  242,  242,  242,  242,
      242,  242,  244,  244,  244,  244,  244,  245,  245,  245,
      245,  245,  245,  246,  246,  246,  246,  246,  248,  248,
      248,  248,  248,  248,  250,  250,  250,  250,  250,  251,
      251,  251,  251,  251,  251,  252,  252,  252,  252,  252,
      260,  143,  260,  260,  260,  260,  260,  260,  261,  261,
      261,  261,  261,  261,  262,  262,  262,  262,  262,  263,
      263,  263,  263,  263,  264,  140,  264,  264,  264,  264,
      264,  266,  136,  266,  266,  266,  266,  266,  266,  267,
      267,  267,  267,  267,  267,  268,  268,  268,  268,  268,

      269,  269,  269,  269,  269,  270,  135,  270,  270,  270,
      270,  270,  276,  276,  276,  276,  276,  276,  279,  279,
      279,  279,  279,  279,  280,  280,  280,  280,  280,  280,
      283,  283,  283,  283,  283,  283,  288,  134,  288,  288,
      288,  288,  288,  288,  289,  289,  289,  289,  289,  289,
      290,  290,  290,  290,  290,  292,  132,  292,  292,  292,
      292,  292,  292,  293,  293,  293,  293,  293,  293,  294,
      294,  294,  294,  294,  300,  300,  300,  300,  300,  300,
      303,  303,  303,  303,  303,  303,  304,  304,  304,  304,
      304,  304,  307,  307,  307,  307,  307,  307,  312,  312,

      312,  312,  312,  312,  314,  314,  314,  314,  314,  316,
      316,  316,  316,  316,  316,  318,  318,  318,  318,  318,
      323,  323,  323,  323,  323,  325,  325,  325,  325,  325,
      330,  330,  330,  330,  330,  330,  330,  330,  330,  330,
      330,  331,  131,  331,  129,  331,  331,  331,  331,  331,
      331,  331,  332,  125,  332,  124,  332,  332,  332,  332,
      332,  332,  332,  333,  122,  116,  333,  333,  333,  333,
      333,  333,  334,  334,  115,  334,  334,  335,  335,  113,
      335,  335,  336,  336,  112,  336,  336,  337,  111,  337,
      337,  337,  337,  337,  337,  337,  337,  338,  110,  338,

      338,  338,  338,  338,  338,  338,  338,  338,  339,  104,
      339,  339,  339,  339,  339,  339,  339,  339,  339,  340,
       98,  340,  340,  340,  340,  340,  340,  340,  340,  341,
       94,   93,   87,   81,   75,   73,   70,  341,  341,  342,
       68,  342,  342,  342,  342,  342,  342,  342,  342,  343,
       63,  343,   62,  343,  343,  343,  343,  343,  343,  343,
      344,   61,  344,   58,  344,  344,  344,  344,  344,  344,
      344,  345,   57,  345,   46,  345,  345,  345,  345,  345,
      345,  345,  346,   42,  346,  346,  346,  346,  346,  346,
      346,  346,  346,  347,   41,  347,   30,  347,  347,  347,

      347,  347,  347,  347,  348,  348,  349,   27,   12,  349,
      349,  350,   11,  350,  350,  350,  350,  350,  350,  350,
      350,  351,    9,  351,    7,  351,  351,  351,  351,  351,
      351,  351,  352,    0,  352,  352,  353,    0,  353,  353,
      354,    0,  354,  354,  355,  355,  356,    0,  356,  357,
        0,  357,  357,  358,    0,  358,  358,  359,    0,  359,
      359,  360,  360,  361,    0,  361,  362,  362,  362,  363,
      363,  363,  364,  364,  364,  365,  365,  366,    0,  366,
      366,  367,    0,  367,  367,  368,    0,  368,  368,  369,
      369,  370,    0,  370,  370,  371,    0,  371,  371,  372,

        0,  372,  372,  373,    0,  373,  373,  374,    0,  374,
      374,  375,    0,  375,  375,  376,  376,  377,    0,  377,
      378,    0,  378,  378,  379,    0,  379,  379,  380,    0,
      380,  380,  381,  381,  382,    0,  382,  383,  383,  384,
      384,  329,  329,  329,  329,  329,  329,  329,  329,  329,
      329,  329,  329,  329,  329,  329,  329,  329,  329,  329,
      329,  329,  329,  329,  329,  329,  329,  329,  329,  329,
      329,  329,  329,  329
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "./parse.lex"
#define INITIAL 0
#line 2 "./parse.lex"
/*
 * Copyright (c) 1996, 1998, 1999 Todd C. Miller <Todd.Miller@courtesan.com>
 * All rights reserved.
 *
 * This code is derived from software contributed by Chris Jepeway
 * <jepeway@cs.utk.edu>
 *
 * This code is derived from software contributed by Chris Jepeway
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 * 1. Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *
 * 2. Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in the
 *    documentation and/or other materials provided with the distribution.
 *
 * 3. The name of the author may not be used to endorse or promote products
 *    derived from this software without specific prior written permission.
 *
 * 4. Products derived from this software may not be called "Sudo" nor
 *    may "Sudo" appear in their names without specific prior written
 *    permission from the author.
 *
 * THIS SOFTWARE IS PROVIDED ``AS IS'' AND ANY EXPRESS OR IMPLIED WARRANTIES,
 * INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY
 * AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.  IN NO EVENT SHALL
 * THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,
 * EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
 * PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS;
 * OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
 * WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR
 * OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF
 * ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */

#include "config.h"

#ifdef STDC_HEADERS
#include <stdlib.h>
#endif /* STDC_HEADERS */
#ifdef HAVE_UNISTD_H
#include <unistd.h>
#endif /* HAVE_UNISTD_H */
#ifdef HAVE_STRING_H
#include <string.h>
#endif /* HAVE_STRING_H */
#if defined(HAVE_MALLOC_H) && !defined(STDC_HEADERS)
#include <malloc.h>
#endif /* HAVE_MALLOC_H && !STDC_HEADERS */
#include <ctype.h>
#include <sys/types.h>
#include <sys/param.h>
#include "sudo.h"
#include "parse.h"
#include "sudo.tab.h"

#ifndef lint
static const char rcsid[] = "$Sudo$";
#endif /* lint */

#undef yywrap		/* guard against a yywrap macro */

extern YYSTYPE yylval;
extern int clearaliases;
int sudolineno = 1;
static int sawspace = 0;
static int arg_len = 0;
static int arg_size = 0;

static void fill		__P((char *, int));
static void fill_cmnd		__P((char *, int));
static void fill_args		__P((char *, int, int));
extern void reset_aliases	__P((void));
extern void yyerror		__P((char *));

/* realloc() to size + COMMANDARGINC to make room for command args */
#define COMMANDARGINC	64

#ifdef TRACELEXER
#define LEXTRACE(msg)	fputs(msg, stderr)
#else
#define LEXTRACE(msg)
#endif
#define GOTCMND 1

#define GOTRUNAS 2

#line 876 "lex.yy.c"

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap YY_PROTO(( void ));
#else
extern int yywrap YY_PROTO(( void ));
#endif
#endif

#ifndef YY_NO_UNPUT
static void yyunput YY_PROTO(( int c, char *buf_ptr ));
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy YY_PROTO(( char *, yyconst char *, int ));
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen YY_PROTO(( yyconst char * ));
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif
#endif

#if YY_STACK_USED
static int yy_start_stack_ptr = 0;
static int yy_start_stack_depth = 0;
static int *yy_start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void yy_push_state YY_PROTO(( int new_state ));
#endif
#ifndef YY_NO_POP_STATE
static void yy_pop_state YY_PROTO(( void ));
#endif
#ifndef YY_NO_TOP_STATE
static int yy_top_state YY_PROTO(( void ));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#ifdef __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( yy_current_buffer->yy_is_interactive ) \
		{ \
		int c = '*', n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else if ( ((result = fread( buf, 1, max_size, yyin )) == 0) \
		  && ferror( yyin ) ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int yylex YY_PROTO(( void ))
#endif

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

YY_DECL
	{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;

#line 102 "./parse.lex"

#line 1029 "lex.yy.c"

	if ( yy_init )
		{
		yy_init = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yy_start )
			yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! yy_current_buffer )
			yy_current_buffer =
				yy_create_buffer( yyin, YY_BUF_SIZE );

		yy_load_buffer_state();
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yy_start;
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				yy_last_accepting_state = yy_current_state;
				yy_last_accepting_cpos = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 330 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 1342 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;


do_action:	/* This label is used only to access EOF actions. */


		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = yy_hold_char;
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 103 "./parse.lex"
{			/* throw away space/tabs */
			    sawspace = TRUE;	/* but remember for fill_args */
			}
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 107 "./parse.lex"
{ 
			    sawspace = TRUE;	/* remember for fill_args */
			    ++sudolineno;
			    LEXTRACE("\n\t");
			}			/* throw away EOL after \ */
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 113 "./parse.lex"
{
			    LEXTRACE("QUOTEDCHAR ");
			    fill_args(yytext + 1, 1, sawspace);
			    sawspace = FALSE;
			}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 119 "./parse.lex"
{
			    BEGIN INITIAL;
			    unput(*yytext);
			    return(COMMAND);
			}			/* end of command line args */
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 125 "./parse.lex"
{ 
			    ++sudolineno; 
			    LEXTRACE("\n");
			    return(COMMENT);
			}			/* return newline */
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 131 "./parse.lex"
{
			    ++sudolineno;
			    LEXTRACE("\n");
			    return(COMMENT);
			}			/* return comments */
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 137 "./parse.lex"
{
			    LEXTRACE("ARG ");
			    fill_args(yytext, yyleng, sawspace);
			    sawspace = FALSE;
			  }			/* a command line arg */
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 143 "./parse.lex"
{
			    LEXTRACE(", ");
			    return(',');
			}			/* return ',' */
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 148 "./parse.lex"
{
			    if (yyleng % 2 == 1)
				return('!');	/* return '!' */
			}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 153 "./parse.lex"
{
			    LEXTRACE("= ");
			    return('=');
			}			/* return '=' */
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 158 "./parse.lex"
{
			    LEXTRACE(": ");
			    return(':');
			}			/* return ':' */
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 163 "./parse.lex"
{ 
				/* cmnd does not require passwd for this user */
			    	LEXTRACE("NOPASSWD ");
			    	return(NOPASSWD);
			}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 169 "./parse.lex"
{ 
				/* cmnd requires passwd for this user */
			    	LEXTRACE("PASSWD ");
			    	return(PASSWD);
			}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 175 "./parse.lex"
{
			    /* netgroup */
			    fill(yytext, yyleng);
			    return(NETGROUP);
			}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 181 "./parse.lex"
{
			    /* UN*X group */
			    fill(yytext, yyleng);
			    return(USERGROUP);
			}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 187 "./parse.lex"
{
			    fill(yytext, yyleng);
			    LEXTRACE("NTWKADDR ");
			    return(NTWKADDR);
			}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 193 "./parse.lex"
{
			    fill(yytext, yyleng);
			    LEXTRACE("NTWKADDR ");
			    return(NTWKADDR);
			}
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 199 "./parse.lex"
{
			    fill(yytext, yyleng);
			    LEXTRACE("FQHOST ");
			    return(FQHOST);
			}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 205 "./parse.lex"
{
				BEGIN GOTRUNAS;
				LEXTRACE("RUNAS ");
				return (RUNAS);
			}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 211 "./parse.lex"
{
			    /* Runas_Alias user can run command as or ALL */
			    if (strcmp(yytext, "ALL") == 0) {
				LEXTRACE("ALL ");
				return(ALL);
			    } else {
				fill(yytext, yyleng);
				LEXTRACE("ALIAS ");
				return(ALIAS);
			    }
			}
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 223 "./parse.lex"
{
			    /* username/uid that user can run command as */
			    fill(yytext, yyleng);
			    LEXTRACE("NAME ");
			    return(NAME);
			}
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 230 "./parse.lex"
BEGIN INITIAL;
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 233 "./parse.lex"
{
			    /* directories can't have args... */
			    if (yytext[yyleng - 1] == '/') {
				LEXTRACE("COMMAND ");
				fill_cmnd(yytext, yyleng);
				return(COMMAND);
			    } else {
				BEGIN GOTCMND;
				LEXTRACE("COMMAND ");
				fill_cmnd(yytext, yyleng);
			    }
			}			/* a pathname */
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 246 "./parse.lex"
{
			    if (strcmp(yytext, "ALL") == 0) {
				LEXTRACE("ALL ");
				return(ALL);
			    } else {
				fill(yytext, yyleng);
				LEXTRACE("ALIAS ");
				return(ALIAS);
			    }
			}
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 257 "./parse.lex"
{
			    fill(yytext, yyleng);
			    if (strcmp(yytext, "Host_Alias") == 0) {
				LEXTRACE("HOSTALIAS ");
				return(HOSTALIAS);
			    }
			    if (strcmp(yytext, "Cmnd_Alias") == 0) {
				LEXTRACE("CMNDALIAS ");
				return(CMNDALIAS);
			    }
			    if (strcmp(yytext, "User_Alias") == 0) {
				LEXTRACE("USERALIAS ");
				return(USERALIAS);
			    }
			    if (strcmp(yytext, "Runas_Alias") == 0) {
				LEXTRACE("RUNASALIAS ");
				return(RUNASALIAS);
			    }

			    /* NAME is what RFC1034 calls a label */
			    LEXTRACE("NAME ");
			    return(NAME);
			}
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 281 "./parse.lex"
{
			    return(ERROR);
			}	/* parse error */
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 285 "./parse.lex"
ECHO;
	YY_BREAK
#line 1376 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(GOTCMND):
case YY_STATE_EOF(GOTRUNAS):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between yy_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yy_n_chars = yy_current_buffer->yy_n_chars;
			yy_current_buffer->yy_input_file = yyin;
			yy_current_buffer->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yy_did_buffer_switch_on_eof = 0;

				if ( yywrap() )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yy_c_buf_p =
					yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yy_c_buf_p =
				&yy_current_buffer->yy_ch_buf[yy_n_chars];

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of yylex */


/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

static int yy_get_next_buffer()
	{
	register char *dest = yy_current_buffer->yy_ch_buf;
	register char *source = yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( yy_current_buffer->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yy_c_buf_p - yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yy_c_buf_p - yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		yy_current_buffer->yy_n_chars = yy_n_chars = 0;

	else
		{
		int num_to_read =
			yy_current_buffer->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = yy_current_buffer;

			int yy_c_buf_p_offset =
				(int) (yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yy_flex_realloc( (void *) b->yy_ch_buf,
							 b->yy_buf_size + 2 );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = yy_current_buffer->yy_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
			yy_n_chars, num_to_read );

		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	if ( yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			yy_current_buffer->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	yy_n_chars += number_to_move;
	yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yytext_ptr = &yy_current_buffer->yy_ch_buf[0];

	return ret_val;
	}


/* yy_get_previous_state - get the state just before the EOB char was reached */

static yy_state_type yy_get_previous_state()
	{
	register yy_state_type yy_current_state;
	register char *yy_cp;

	yy_current_state = yy_start;

	for ( yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			yy_last_accepting_state = yy_current_state;
			yy_last_accepting_cpos = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 330 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
	}


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static yy_state_type yy_try_NUL_trans( yy_state_type yy_current_state )
#else
static yy_state_type yy_try_NUL_trans( yy_current_state )
yy_state_type yy_current_state;
#endif
	{
	register int yy_is_jam;
	register char *yy_cp = yy_c_buf_p;

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		yy_last_accepting_state = yy_current_state;
		yy_last_accepting_cpos = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 330 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 329);

	return yy_is_jam ? 0 : yy_current_state;
	}


#ifndef YY_NO_UNPUT
#ifdef YY_USE_PROTOS
static void yyunput( int c, register char *yy_bp )
#else
static void yyunput( c, yy_bp )
int c;
register char *yy_bp;
#endif
	{
	register char *yy_cp = yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yy_hold_char;

	if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = yy_n_chars + 2;
		register char *dest = &yy_current_buffer->yy_ch_buf[
					yy_current_buffer->yy_buf_size + 2];
		register char *source =
				&yy_current_buffer->yy_ch_buf[number_to_move];

		while ( source > yy_current_buffer->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		yy_current_buffer->yy_n_chars =
			yy_n_chars = yy_current_buffer->yy_buf_size;

		if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;


	yytext_ptr = yy_bp;
	yy_hold_char = *yy_cp;
	yy_c_buf_p = yy_cp;
	}
#endif	/* ifndef YY_NO_UNPUT */


#ifdef __cplusplus
static int yyinput()
#else
static int input()
#endif
	{
	int c;

	*yy_c_buf_p = yy_hold_char;

	if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			/* This was really a NUL. */
			*yy_c_buf_p = '\0';

		else
			{ /* need more input */
			int offset = yy_c_buf_p - yytext_ptr;
			++yy_c_buf_p;

			switch ( yy_get_next_buffer() )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/* fall through */

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap() )
						return EOF;

					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yy_c_buf_p = yytext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) yy_c_buf_p;	/* cast for 8-bit char's */
	*yy_c_buf_p = '\0';	/* preserve yytext */
	yy_hold_char = *++yy_c_buf_p;


	return c;
	}


#ifdef YY_USE_PROTOS
void yyrestart( FILE *input_file )
#else
void yyrestart( input_file )
FILE *input_file;
#endif
	{
	if ( ! yy_current_buffer )
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

	yy_init_buffer( yy_current_buffer, input_file );
	yy_load_buffer_state();
	}


#ifdef YY_USE_PROTOS
void yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void yy_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif
	{
	if ( yy_current_buffer == new_buffer )
		return;

	if ( yy_current_buffer )
		{
		/* Flush out information for old buffer. */
		*yy_c_buf_p = yy_hold_char;
		yy_current_buffer->yy_buf_pos = yy_c_buf_p;
		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	yy_current_buffer = new_buffer;
	yy_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yy_did_buffer_switch_on_eof = 1;
	}


#ifdef YY_USE_PROTOS
void yy_load_buffer_state( void )
#else
void yy_load_buffer_state()
#endif
	{
	yy_n_chars = yy_current_buffer->yy_n_chars;
	yytext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
	yyin = yy_current_buffer->yy_input_file;
	yy_hold_char = *yy_c_buf_p;
	}


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE yy_create_buffer( file, size )
FILE *file;
int size;
#endif
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yy_flex_alloc( b->yy_buf_size + 2 );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
	}


#ifdef YY_USE_PROTOS
void yy_delete_buffer( YY_BUFFER_STATE b )
#else
void yy_delete_buffer( b )
YY_BUFFER_STATE b;
#endif
	{
	if ( ! b )
		return;

	if ( b == yy_current_buffer )
		yy_current_buffer = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yy_flex_free( (void *) b->yy_ch_buf );

	yy_flex_free( (void *) b );
	}


#ifndef YY_ALWAYS_INTERACTIVE
#ifndef YY_NEVER_INTERACTIVE
extern int isatty YY_PROTO(( int ));
#endif
#endif

#ifdef YY_USE_PROTOS
void yy_init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void yy_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif


	{
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

#if YY_ALWAYS_INTERACTIVE
	b->yy_is_interactive = 1;
#else
#if YY_NEVER_INTERACTIVE
	b->yy_is_interactive = 0;
#else
	b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
#endif
#endif
	}


#ifdef YY_USE_PROTOS
void yy_flush_buffer( YY_BUFFER_STATE b )
#else
void yy_flush_buffer( b )
YY_BUFFER_STATE b;
#endif

	{
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == yy_current_buffer )
		yy_load_buffer_state();
	}


#ifndef YY_NO_SCAN_BUFFER
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_buffer( char *base, yy_size_t size )
#else
YY_BUFFER_STATE yy_scan_buffer( base, size )
char *base;
yy_size_t size;
#endif
	{
	YY_BUFFER_STATE b;

	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b );

	return b;
	}
#endif


#ifndef YY_NO_SCAN_STRING
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_string( yyconst char *yy_str )
#else
YY_BUFFER_STATE yy_scan_string( yy_str )
yyconst char *yy_str;
#endif
	{
	int len;
	for ( len = 0; yy_str[len]; ++len )
		;

	return yy_scan_bytes( yy_str, len );
	}
#endif


#ifndef YY_NO_SCAN_BYTES
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_bytes( yyconst char *bytes, int len )
#else
YY_BUFFER_STATE yy_scan_bytes( bytes, len )
yyconst char *bytes;
int len;
#endif
	{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;

	/* Get memory for full buffer, including space for trailing EOB's. */
	n = len + 2;
	buf = (char *) yy_flex_alloc( n );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < len; ++i )
		buf[i] = bytes[i];

	buf[len] = buf[len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
	}
#endif


#ifndef YY_NO_PUSH_STATE
#ifdef YY_USE_PROTOS
static void yy_push_state( int new_state )
#else
static void yy_push_state( new_state )
int new_state;
#endif
	{
	if ( yy_start_stack_ptr >= yy_start_stack_depth )
		{
		yy_size_t new_size;

		yy_start_stack_depth += YY_START_STACK_INCR;
		new_size = yy_start_stack_depth * sizeof( int );

		if ( ! yy_start_stack )
			yy_start_stack = (int *) yy_flex_alloc( new_size );

		else
			yy_start_stack = (int *) yy_flex_realloc(
					(void *) yy_start_stack, new_size );

		if ( ! yy_start_stack )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	yy_start_stack[yy_start_stack_ptr++] = YY_START;

	BEGIN(new_state);
	}
#endif


#ifndef YY_NO_POP_STATE
static void yy_pop_state()
	{
	if ( --yy_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(yy_start_stack[yy_start_stack_ptr]);
	}
#endif


#ifndef YY_NO_TOP_STATE
static int yy_top_state()
	{
	return yy_start_stack[yy_start_stack_ptr - 1];
	}
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

#ifdef YY_USE_PROTOS
static void yy_fatal_error( yyconst char msg[] )
#else
static void yy_fatal_error( msg )
char msg[];
#endif
	{
	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
	}



/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		yytext[yyleng] = yy_hold_char; \
		yy_c_buf_p = yytext + n; \
		yy_hold_char = *yy_c_buf_p; \
		*yy_c_buf_p = '\0'; \
		yyleng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef yytext_ptr
#ifdef YY_USE_PROTOS
static void yy_flex_strncpy( char *s1, yyconst char *s2, int n )
#else
static void yy_flex_strncpy( s1, s2, n )
char *s1;
yyconst char *s2;
int n;
#endif
	{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif

#ifdef YY_NEED_STRLEN
#ifdef YY_USE_PROTOS
static int yy_flex_strlen( yyconst char *s )
#else
static int yy_flex_strlen( s )
yyconst char *s;
#endif
	{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
	}
#endif


#ifdef YY_USE_PROTOS
static void *yy_flex_alloc( yy_size_t size )
#else
static void *yy_flex_alloc( size )
yy_size_t size;
#endif
	{
	return (void *) malloc( size );
	}

#ifdef YY_USE_PROTOS
static void *yy_flex_realloc( void *ptr, yy_size_t size )
#else
static void *yy_flex_realloc( ptr, size )
void *ptr;
yy_size_t size;
#endif
	{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
	}

#ifdef YY_USE_PROTOS
static void yy_flex_free( void *ptr )
#else
static void yy_flex_free( ptr )
void *ptr;
#endif
	{
	free( ptr );
	}

#if YY_MAIN
int main()
	{
	yylex();
	return 0;
	}
#endif
#line 285 "./parse.lex"

static void
fill(s, len)
    char *s;
    int len;
{
    yylval.string = (char *) malloc(len + 1);
    if (yylval.string == NULL)
	yyerror("unable to allocate memory");

    /* copy the string and NULL-terminate it */
    (void) strncpy(yylval.string, s, len);
    yylval.string[len] = '\0';
}

static void
fill_cmnd(s, len)
    char *s;
    int len;
{
    arg_len = arg_size = 0;

    yylval.command.cmnd = (char *) malloc(len + 1);
    if (yylval.command.cmnd == NULL)
	yyerror("unable to allocate memory");

    /* copy the string and NULL-terminate it */
    (void) strncpy(yylval.command.cmnd, s, len);
    yylval.command.cmnd[len] = '\0';

    yylval.command.args = NULL;
}

static void
fill_args(s, len, addspace)
    char *s;
    int len;
    int addspace;
{
    int new_len;
    char *p;

    /*
     * If first arg, malloc() some room, else if we don't
     * have enough space realloc() some more.
     */
    if (yylval.command.args == NULL) {
	addspace = 0;
	new_len = len;

	while (new_len >= (arg_size += COMMANDARGINC))
	    ;

	yylval.command.args = (char *) malloc(arg_size);
	if (yylval.command.args == NULL)
	    yyerror("unable to allocate memory");
    } else {
	new_len = arg_len + len + addspace;

	if (new_len >= arg_size) {
	    /* Allocate more space than we need for subsequent args */
	    while (new_len >= (arg_size += COMMANDARGINC))
		;

	    if ((p = (char *) realloc(yylval.command.args, arg_size)) == NULL) {
		free(yylval.command.args);
		yyerror("unable to allocate memory");
	    } else
		yylval.command.args = p;
	}
    }

    /* Efficiently append the arg (with a leading space if needed). */
    p = yylval.command.args + arg_len;
    if (addspace)
	*p++ = ' ';
    (void) strcpy(p, s);
    arg_len = new_len;
}

int
yywrap()
{
#ifdef YY_NEW_FILE
    YY_NEW_FILE;
#endif /* YY_NEW_FILE */

    /* Don't reset the aliases if called by testsudoers. */
    if (clearaliases)
	reset_aliases();

    return(TRUE);
}
